# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/peter/DOSCODE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/peter/DOSCODE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peter/DOSCODE/CMakeFiles /home/peter/DOSCODE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peter/DOSCODE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named QUAD

# Build rule for target.
QUAD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 QUAD
.PHONY : QUAD

# fast build rule for target.
QUAD/fast:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/build
.PHONY : QUAD/fast

BSP.o: BSP.C.o

.PHONY : BSP.o

# target to build an object file
BSP.C.o:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/BSP.C.o
.PHONY : BSP.C.o

BSP.i: BSP.C.i

.PHONY : BSP.i

# target to preprocess a source file
BSP.C.i:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/BSP.C.i
.PHONY : BSP.C.i

BSP.s: BSP.C.s

.PHONY : BSP.s

# target to generate assembly for a file
BSP.C.s:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/BSP.C.s
.PHONY : BSP.C.s

GFX.o: GFX.C.o

.PHONY : GFX.o

# target to build an object file
GFX.C.o:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/GFX.C.o
.PHONY : GFX.C.o

GFX.i: GFX.C.i

.PHONY : GFX.i

# target to preprocess a source file
GFX.C.i:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/GFX.C.i
.PHONY : GFX.C.i

GFX.s: GFX.C.s

.PHONY : GFX.s

# target to generate assembly for a file
GFX.C.s:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/GFX.C.s
.PHONY : GFX.C.s

KEY_INPUT.o: KEY_INPUT.C.o

.PHONY : KEY_INPUT.o

# target to build an object file
KEY_INPUT.C.o:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/KEY_INPUT.C.o
.PHONY : KEY_INPUT.C.o

KEY_INPUT.i: KEY_INPUT.C.i

.PHONY : KEY_INPUT.i

# target to preprocess a source file
KEY_INPUT.C.i:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/KEY_INPUT.C.i
.PHONY : KEY_INPUT.C.i

KEY_INPUT.s: KEY_INPUT.C.s

.PHONY : KEY_INPUT.s

# target to generate assembly for a file
KEY_INPUT.C.s:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/KEY_INPUT.C.s
.PHONY : KEY_INPUT.C.s

MAIN_VGA.o: MAIN_VGA.C.o

.PHONY : MAIN_VGA.o

# target to build an object file
MAIN_VGA.C.o:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/MAIN_VGA.C.o
.PHONY : MAIN_VGA.C.o

MAIN_VGA.i: MAIN_VGA.C.i

.PHONY : MAIN_VGA.i

# target to preprocess a source file
MAIN_VGA.C.i:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/MAIN_VGA.C.i
.PHONY : MAIN_VGA.C.i

MAIN_VGA.s: MAIN_VGA.C.s

.PHONY : MAIN_VGA.s

# target to generate assembly for a file
MAIN_VGA.C.s:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/MAIN_VGA.C.s
.PHONY : MAIN_VGA.C.s

MATH.o: MATH.C.o

.PHONY : MATH.o

# target to build an object file
MATH.C.o:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/MATH.C.o
.PHONY : MATH.C.o

MATH.i: MATH.C.i

.PHONY : MATH.i

# target to preprocess a source file
MATH.C.i:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/MATH.C.i
.PHONY : MATH.C.i

MATH.s: MATH.C.s

.PHONY : MATH.s

# target to generate assembly for a file
MATH.C.s:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/MATH.C.s
.PHONY : MATH.C.s

WALL.o: WALL.C.o

.PHONY : WALL.o

# target to build an object file
WALL.C.o:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/WALL.C.o
.PHONY : WALL.C.o

WALL.i: WALL.C.i

.PHONY : WALL.i

# target to preprocess a source file
WALL.C.i:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/WALL.C.i
.PHONY : WALL.C.i

WALL.s: WALL.C.s

.PHONY : WALL.s

# target to generate assembly for a file
WALL.C.s:
	$(MAKE) -f CMakeFiles/QUAD.dir/build.make CMakeFiles/QUAD.dir/WALL.C.s
.PHONY : WALL.C.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... QUAD"
	@echo "... BSP.o"
	@echo "... BSP.i"
	@echo "... BSP.s"
	@echo "... GFX.o"
	@echo "... GFX.i"
	@echo "... GFX.s"
	@echo "... KEY_INPUT.o"
	@echo "... KEY_INPUT.i"
	@echo "... KEY_INPUT.s"
	@echo "... MAIN_VGA.o"
	@echo "... MAIN_VGA.i"
	@echo "... MAIN_VGA.s"
	@echo "... MATH.o"
	@echo "... MATH.i"
	@echo "... MATH.s"
	@echo "... WALL.o"
	@echo "... WALL.i"
	@echo "... WALL.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

